name: Reusable workflow example

on:
  workflow_call:
jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
    - name: print hello
      run: echo hello
    - name: print path
      run: pwd
    - name: display dir
      run: ls -la