name: Reusable workflow example

on:
  workflow_call:
    inputs:
      name:
        required: true 
        type: string
jobs:
  PHP-Composer:
    runs-on: ubuntu-latest
    steps:
    
    - name: print hello
      run: echo hello ${{ inputs.name }}
    
    - name: print repo
      run: echo reponame ${{ GITHUB_REPOSITORY }}
    
    - name: print path
      run: pwd

    - name: display dir
      run: ls -la

    - name: check php version
      run: php --version
    
    - uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'
        tools: pecl
        extensions: swoole

    - name: check php version
      run: php --version
      
    - uses: dmyst3/INSTALL-PHP@main
      with:
        version: '8.1'
