name: Reusable workflow example

on:
  workflow_call:
    inputs:
      name:
        required: true 
        type: string
jobs:
  PHP-Composer:
    runs-on: ubuntu-latest
    steps:
    
    - name: print hello
      run: echo hello ${{ inputs.name }}
    
    - name: print repo
      run: "echo reponame ${GITHUB_REPOSITORY}"
    
    - name: print info
      run: |
          echo "Home: ${HOME}"
          echo "GITHUB_WORKFLOW: ${GITHUB_WORKFLOW}"
          echo "GITHUB_ACTIONS: ${GITHUB_ACTIONS}"
          echo "GITHUB_ACTOR: ${GITHUB_ACTOR}"
          echo "GITHUB_REPOSITORY: ${GITHUB_REPOSITORY}"
          echo "GITHUB_EVENT_NAME: ${GITHUB_EVENT_NAME}"
          echo "GITHUB_WORKSPACE: ${GITHUB_WORKSPACE}"
          echo "GITHUB_SHA: ${GITHUB_SHA}"
          echo "GITHUB_REF: ${GITHUB_REF}"

    - name: check php version
      run: php --version
    
      
    - uses: dmyst3/INSTALL-PHP@main
      with:
        version: '8.1'
        
    - uses: dmyst3/INSTALL-Composer@main

        
    - name: check php version
      run: php --version
